name: Greetings

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Greetings from GS Asansol! Thanks for making the PR, our team will soon review your PR. Thanks :)"
